# Generated by Django 5.2.11 on 2026-02-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='e.g. tayara, mubawab', max_length=50)),
                ('source_url', models.URLField(help_text='Original listing URL', unique=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('property_type', models.CharField(choices=[('apartment', 'Appartement'), ('house', 'Maison'), ('villa', 'Villa'), ('studio', 'Studio'), ('land', 'Terrain'), ('commercial', 'Commercial'), ('other', 'Autre')], default='other', max_length=30)),
                ('transaction_type', models.CharField(choices=[('sale', 'Vente'), ('rent', 'Location')], default='sale', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='TND', max_length=5)),
                ('area_m2', models.FloatField(blank=True, help_text='Surface in m²', null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('governorate', models.CharField(blank=True, default='', max_length=50)),
                ('delegation', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text="e.g. ['climatisé', 'parking']")),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('status', models.CharField(choices=[('bronze', 'Bronze — Raw scraped'), ('silver', 'Silver — Extracted & validated'), ('gold', 'Gold — Enriched & geocoded')], default='bronze', max_length=10)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('raw_html_key', models.CharField(blank=True, default='', help_text='MinIO object key for raw HTML', max_length=200)),
                ('raw_extracted', models.JSONField(blank=True, default=dict, help_text='Raw LLM extraction output')),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['source'], name='listings_li_source_b550ff_idx'), models.Index(fields=['status'], name='listings_li_status_63af6d_idx'), models.Index(fields=['governorate'], name='listings_li_governo_5b8d6a_idx'), models.Index(fields=['property_type'], name='listings_li_propert_7a505c_idx'), models.Index(fields=['transaction_type'], name='listings_li_transac_79321a_idx'), models.Index(fields=['price'], name='listings_li_price_d6caaa_idx')],
            },
        ),
    ]
